name: Elm Checks
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: yarn
    - name: Add yarn bin to path
      run: echo ::add-path::$(yarn bin)
    - name: Run elm-test
      run: elm-test
    - name: Run elm-review
      run: elm-review
    - uses: sparksp/elm-format-action@v1
      with:
        elm_files: |
          src/**/*.elm
          !**/Tailwind.elm
        elm_glob: true