name: Elm Checks

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: yarn
    - name: Run elm-test
      run: yarn run elm-test
    - name: Run elm-review
      run: yarn run elm-review
    - name: Run elm-format
      run: find src -name '*.elm' ! -name Tailwind.elm | xargs yarn run elm-format --validate